fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "1.8.0"
  symlinks:
    gitlab: "#{source_dir}"
